# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/xilinix_lab/number_recognize/number_recognize.cache/wt [current_project]
set_property parent.project_path D:/xilinix_lab/number_recognize/number_recognize.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/xilinix_lab/IP_Core [current_project]
update_ip_catalog
set_property ip_output_repo d:/xilinix_lab/number_recognize/number_recognize.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Driver_Bayer_To_RGB.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Driver_Csi_To_Dvp.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Driver_IIC.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Driver_MIPI.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Num_Display.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/OV5647_Init.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/RGB2Binary.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Rgb_Led.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/Trigger_Generator.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/num2digital.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/posedge_detection.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/pre_recognize.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/recognize.v
  D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/new/main.v
}
read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_1_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_1_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_1_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_1_1/clk_wiz_1_ooc.xdc]

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc]

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/AXIS_Data_RAM/AXIS_Data_RAM.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/AXIS_Data_RAM/AXIS_Data_RAM_ooc.xdc]

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/RAM_Line/RAM_Line.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/RAM_Line/RAM_Line_ooc.xdc]

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/csi_to_axis_0/csi_to_axis_0.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/csi_to_axis_0/hdl/csi_to_axis.xdc]

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Clk_Division_0/Clk_Division_0.xci

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_SK6805_0/Driver_SK6805_0.xci

read_ip -quiet D:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/xilinix_lab/number_recognize/number_recognize.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files D:/xilinix_lab/number_recognize/number_recognize.srcs/constrs_1/new/system.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
