# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/Driver_MIPI_0.xci
# IP: The module: 'Driver_MIPI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi_to_axis_0/csi_to_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] -quiet

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] -quiet

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi_to_axis_0/hdl/csi_to_axis.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/Driver_MIPI_0.xci
# IP: The module: 'Driver_MIPI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi_to_axis_0/csi_to_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] -quiet

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] -quiet

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi_to_axis_0/hdl/csi_to_axis.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: d:/xilinix_lab/number_recognize/number_recognize.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
